#!/bin/sh

# Get all the staged (HTML, SCSS, TS) files 
FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.ts" "*.html" "*.scss" | sed 's| |\\ |g')

# I believe if there are no staged (HTML, SCSS, TS) files, then the script will finish
[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo "$FILES" | xargs ./frontend/lilypad-sportcred-frontend/node_modules/.bin/prettier --write

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0
